package id.luckynetwork.dev.lyrams.lej.versionsupport.v1_19_R1.enums;

import lombok.Getter;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

@SuppressWarnings({"unused", "SpellCheckingInspection"})
public enum LItemStack {

    COBBLE(new ItemStack(Material.COBBLESTONE, 1)),
    STONEBRICK(new ItemStack(Material.STONE_BRICKS, 1)),
    GRANITE(new ItemStack(Material.STONE, 1)),
    POLISHEDGRANITE(new ItemStack(Material.STONE, 1)),
    DIROITE(new ItemStack(Material.STONE, 1)),
    POLISHEDDIROITE(new ItemStack(Material.STONE, 1)),
    ANDESITE(new ItemStack(Material.STONE, 1)),
    POLISHEDANDESITE(new ItemStack(Material.STONE, 1)),
    ENDSTONE(new ItemStack(Material.END_STONE, 1)),

    COARSEDIRT(new ItemStack(Material.DIRT, 1)),
    PODZOL(new ItemStack(Material.DIRT, 1)),

    WOOD(new ItemStack(Material.OAK_WOOD, 1)),
    OAKWOOD(new ItemStack(Material.OAK_WOOD, 1)),
    SPRUCEWOOD(new ItemStack(Material.SPRUCE_WOOD, 1)),
    BIRCHWOOD(new ItemStack(Material.BIRCH_WOOD, 1)),
    JUNGLEWOOD(new ItemStack(Material.JUNGLE_WOOD, 1)),
    ACACIAWOOD(new ItemStack(Material.ACACIA_WOOD, 1)),
    DARKOAKWOOD(new ItemStack(Material.DARK_OAK_WOOD, 1)),

    SAPLING(new ItemStack(Material.OAK_SAPLING, 1)),
    OAKSAPLING(new ItemStack(Material.OAK_SAPLING, 1)),
    SPRUCESAPLING(new ItemStack(Material.SPRUCE_SAPLING, 1)),
    BIRCHSAPLING(new ItemStack(Material.BIRCH_SAPLING, 1)),
    JUNGLESAPLING(new ItemStack(Material.JUNGLE_SAPLING, 1)),
    ACACIASAPLING(new ItemStack(Material.ACACIA_SAPLING, 1)),
    DARKOAKSAPLING(new ItemStack(Material.DARK_OAK_SAPLING, 1)),

    TRAPDOOR(new ItemStack(Material.OAK_TRAPDOOR, 1)),
    OAKTRAPDOOR(new ItemStack(Material.OAK_TRAPDOOR, 1)),
    SPRUCETRAPDOOR(new ItemStack(Material.SPRUCE_TRAPDOOR, 1)),
    BIRCHTRAPDOOR(new ItemStack(Material.BIRCH_TRAPDOOR, 1)),
    JUNGLETRAPDOOR(new ItemStack(Material.JUNGLE_TRAPDOOR, 1)),
    ACACIATRAPDOOR(new ItemStack(Material.ACACIA_TRAPDOOR, 1)),
    DARKOAKTRAPDOOR(new ItemStack(Material.DARK_OAK_TRAPDOOR, 1)),
    IRONTRAPDOOR(new ItemStack(Material.IRON_TRAPDOOR, 1)),

    DOOR(new ItemStack(Material.OAK_DOOR, 1)),
    IRONDOOR(new ItemStack(Material.IRON_DOOR, 1)),
    OAKDOOR(new ItemStack(Material.OAK_DOOR, 1)),
    SPRUCEDOOR(new ItemStack(Material.SPRUCE_DOOR, 1)),
    BIRCHDOOR(new ItemStack(Material.BIRCH_DOOR, 1)),
    JUNGLEDOOR(new ItemStack(Material.JUNGLE_DOOR, 1)),
    ACACIADOOR(new ItemStack(Material.ACACIA_DOOR, 1)),
    DARKOAKDOOR(new ItemStack(Material.DARK_OAK_DOOR, 1)),

    BARS(new ItemStack(Material.IRON_BARS, 1)),
    IRONBAR(new ItemStack(Material.IRON_BARS, 1)),
    BARDING(new ItemStack(Material.IRON_BARS, 1)),
    BAR(new ItemStack(Material.IRON_BARS, 1)),

    REDSAND(new ItemStack(Material.SAND, 1)),
    SOULSAND(new ItemStack(Material.SOUL_SAND, 1)),

    GOLDINGOT(new ItemStack(Material.GOLD_INGOT, 1)),
    IRONINGOT(new ItemStack(Material.IRON_INGOT, 1)),

    GOLDORE(new ItemStack(Material.GOLD_ORE, 1)),
    IRONORE(new ItemStack(Material.IRON_ORE, 1)),
    COALORE(new ItemStack(Material.COAL_ORE, 1)),
    LAPISORE(new ItemStack(Material.LAPIS_ORE, 1)),
    DIAMONDORE(new ItemStack(Material.DIAMOND_ORE, 1)),
    REDSTONEORE(new ItemStack(Material.REDSTONE_ORE, 1)),
    EMERALDORE(new ItemStack(Material.EMERALD_ORE, 1)),
    QUARTZORE(new ItemStack(Material.NETHER_QUARTZ_ORE, 1)),

    GOLDBLOCK(new ItemStack(Material.GOLD_BLOCK, 1)),
    IRONBLOCK(new ItemStack(Material.IRON_BLOCK, 1)),
    COALBLOCK(new ItemStack(Material.COAL_BLOCK, 1)),
    LAPISBLOCK(new ItemStack(Material.LAPIS_BLOCK, 1)),
    DIAMONDBLOCK(new ItemStack(Material.DIAMOND_BLOCK, 1)),
    REDSTONEBLOCK(new ItemStack(Material.REDSTONE_BLOCK, 1)),
    EMERALDBLOCK(new ItemStack(Material.EMERALD_BLOCK, 1)),

    OAKLOG(new ItemStack(Material.OAK_LOG, 1)),
    SPRUCELOG(new ItemStack(Material.SPRUCE_LOG, 1)),
    BIRCHLOG(new ItemStack(Material.BIRCH_LOG, 1)),
    JUNGLELOG(new ItemStack(Material.JUNGLE_LOG, 1)),
    ACACIALOG(new ItemStack(Material.ACACIA_LOG, 1)),
    DARKOAKLOG(new ItemStack(Material.DARK_OAK_LOG, 1)),

    OAKLEAVES(new ItemStack(Material.OAK_LEAVES, 1)),
    OAKLEAF(new ItemStack(Material.OAK_LEAVES, 1)),
    SPRUCELEAVES(new ItemStack(Material.SPRUCE_LEAVES, 1)),
    SPRUCELEAF(new ItemStack(Material.SPRUCE_LEAVES, 1)),
    BIRCHLEAVES(new ItemStack(Material.BIRCH_LEAVES, 1)),
    BIRCHLEAF(new ItemStack(Material.BIRCH_LEAVES, 1)),
    JUNGLELEAVES(new ItemStack(Material.JUNGLE_LEAVES, 1)),
    JUNGLELEAF(new ItemStack(Material.JUNGLE_LEAVES, 1)),
    ACACIALEAVES(new ItemStack(Material.ACACIA_LEAVES, 1)),
    ACACIALEAF(new ItemStack(Material.ACACIA_LEAVES, 1)),
    DARKOAKLEAVES(new ItemStack(Material.DARK_OAK_LEAVES, 1)),
    DARKOAKLEAF(new ItemStack(Material.DARK_OAK_LEAVES, 1)),

    CHISELEDSANDSTONE(new ItemStack(Material.SANDSTONE, 1)),
    SMOOTHSANDSTONE(new ItemStack(Material.SANDSTONE, 1)),

    POWEREDRAIL(new ItemStack(Material.POWERED_RAIL, 1)),
    DETECTORRAIL(new ItemStack(Material.DETECTOR_RAIL, 1)),

    WOOL(new ItemStack(Material.WHITE_WOOL, 1)),
    ORANGEWOOL(new ItemStack(Material.ORANGE_WOOL, 1)),
    MAGENTAWOOL(new ItemStack(Material.MAGENTA_WOOL, 1)),
    LIGHTBLUEWOOL(new ItemStack(Material.LIGHT_BLUE_WOOL, 1)),
    YELLOWWOOL(new ItemStack(Material.YELLOW_WOOL, 1)),
    LIMEWOOL(new ItemStack(Material.LIME_WOOL, 1)),
    PINKWOOL(new ItemStack(Material.PINK_WOOL, 1)),
    GRAYWOOL(new ItemStack(Material.GRAY_WOOL, 1)),
    LIGHTGRAYWOOL(new ItemStack(Material.LIGHT_GRAY_WOOL, 1)),
    CYANWOOL(new ItemStack(Material.CYAN_WOOL, 1)),
    PURPLEWOOL(new ItemStack(Material.PURPLE_WOOL, 1)),
    BLUEWOOL(new ItemStack(Material.BLUE_WOOL, 1)),
    BROWNWOOL(new ItemStack(Material.BROWN_WOOL, 1)),
    GREENWOOL(new ItemStack(Material.GREEN_WOOL, 1)),
    REDWOOL(new ItemStack(Material.RED_WOOL, 1)),
    BLACKWOOL(new ItemStack(Material.BLACK_WOOL, 1)),

    CARPET(new ItemStack(Material.WHITE_CARPET, 1)),
    ORANGECARPET(new ItemStack(Material.ORANGE_CARPET, 1)),
    MAGENTACARPET(new ItemStack(Material.MAGENTA_CARPET, 1)),
    LIGHTBLUECARPET(new ItemStack(Material.LIGHT_BLUE_CARPET, 1)),
    YELLOWCARPET(new ItemStack(Material.YELLOW_CARPET, 1)),
    LIMECARPET(new ItemStack(Material.LIME_CARPET, 1)),
    PINKCARPET(new ItemStack(Material.PINK_CARPET, 1)),
    GRAYCARPET(new ItemStack(Material.GRAY_CARPET, 1)),
    LIGHTGRAYCARPET(new ItemStack(Material.LIGHT_GRAY_CARPET, 1)),
    CYANCARPET(new ItemStack(Material.CYAN_CARPET, 1)),
    PURPLECARPET(new ItemStack(Material.PURPLE_CARPET, 1)),
    BLUECARPET(new ItemStack(Material.BLUE_CARPET, 1)),
    BROWNCARPET(new ItemStack(Material.BROWN_CARPET, 1)),
    GREENCARPET(new ItemStack(Material.GREEN_CARPET, 1)),
    REDCARPET(new ItemStack(Material.RED_CARPET, 1)),
    BLACKCARPET(new ItemStack(Material.BLACK_CARPET, 1)),

    BANNER(new ItemStack(Material.WHITE_BANNER, 1)),
    WHITEBANNER(new ItemStack(Material.WHITE_BANNER, 1)),
    ORANGEBANNER(new ItemStack(Material.ORANGE_BANNER, 1)),
    MAGENTABANNER(new ItemStack(Material.MAGENTA_BANNER, 1)),
    LIGHTBLUEBANNER(new ItemStack(Material.LIGHT_BLUE_BANNER, 1)),
    YELLOWBANNER(new ItemStack(Material.YELLOW_BANNER, 1)),
    LIMEBANNER(new ItemStack(Material.LIME_BANNER, 1)),
    PINKBANNER(new ItemStack(Material.PINK_BANNER, 1)),
    GRAYBANNER(new ItemStack(Material.GRAY_BANNER, 1)),
    LIGHTGRAYBANNER(new ItemStack(Material.LIGHT_GRAY_BANNER, 1)),
    CYANBANNER(new ItemStack(Material.CYAN_BANNER, 1)),
    PURPLEBANNER(new ItemStack(Material.PURPLE_BANNER, 1)),
    BLUEBANNER(new ItemStack(Material.BLUE_BANNER, 1)),
    BROWNBANNER(new ItemStack(Material.BROWN_BANNER, 1)),
    GREENBANNER(new ItemStack(Material.GREEN_BANNER, 1)),
    REDBANNER(new ItemStack(Material.RED_BANNER, 1)),
    BLACKBANNER(new ItemStack(Material.BLACK_BANNER, 1)),

    WHITESTAINEDGLASS(new ItemStack(Material.WHITE_STAINED_GLASS, 1)),
    WHITEGLASS(new ItemStack(Material.WHITE_STAINED_GLASS, 1)),
    ORANGESTAINEDGLASS(new ItemStack(Material.ORANGE_STAINED_GLASS, 1)),
    ORANGEGLASS(new ItemStack(Material.ORANGE_STAINED_GLASS, 1)),
    MAGENTASTAINEDGLASS(new ItemStack(Material.MAGENTA_STAINED_GLASS, 1)),
    MAGENTAGLASS(new ItemStack(Material.MAGENTA_STAINED_GLASS, 1)),
    LIGHTBLUESTAINEDGLASS(new ItemStack(Material.LIGHT_BLUE_STAINED_GLASS, 1)),
    LIGHTBLUEGLASS(new ItemStack(Material.LIGHT_BLUE_STAINED_GLASS, 1)),
    YELLOWSTAINEDGLASS(new ItemStack(Material.YELLOW_STAINED_GLASS, 1)),
    YELLOWGLASS(new ItemStack(Material.YELLOW_STAINED_GLASS, 1)),
    LIMESTAINEDGLASS(new ItemStack(Material.LIME_STAINED_GLASS, 1)),
    LIMEGLASS(new ItemStack(Material.LIME_STAINED_GLASS, 1)),
    PINKSTAINEDGLASS(new ItemStack(Material.PINK_STAINED_GLASS, 1)),
    PINKGLASS(new ItemStack(Material.PINK_STAINED_GLASS, 1)),
    GRAYSTAINEDGLASS(new ItemStack(Material.GRAY_STAINED_GLASS, 1)),
    GRAYGLASS(new ItemStack(Material.GRAY_STAINED_GLASS, 1)),
    LIGHTGRAYSTAINEDGLASS(new ItemStack(Material.LIGHT_GRAY_STAINED_GLASS, 1)),
    LIGHTGRAYGLASS(new ItemStack(Material.LIGHT_GRAY_STAINED_GLASS, 1)),
    CYANSTAINEDGLASS(new ItemStack(Material.CYAN_STAINED_GLASS, 1)),
    CYANGLASS(new ItemStack(Material.CYAN_STAINED_GLASS, 1)),
    PURPLESTAINEDGLASS(new ItemStack(Material.PURPLE_STAINED_GLASS, 1)),
    PURPLEGLASS(new ItemStack(Material.PURPLE_STAINED_GLASS, 1)),
    BLUESTAINEDGLASS(new ItemStack(Material.BLUE_STAINED_GLASS, 1)),
    BLUEGLASS(new ItemStack(Material.BLUE_STAINED_GLASS, 1)),
    BROWNSTAINEDGLASS(new ItemStack(Material.BROWN_STAINED_GLASS, 1)),
    BROWNGLASS(new ItemStack(Material.BROWN_STAINED_GLASS, 1)),
    GREENSTAINEDGLASS(new ItemStack(Material.GREEN_STAINED_GLASS, 1)),
    GREENGLASS(new ItemStack(Material.GREEN_STAINED_GLASS, 1)),
    REDSTAINEDGLASS(new ItemStack(Material.RED_STAINED_GLASS, 1)),
    REDGLASS(new ItemStack(Material.RED_STAINED_GLASS, 1)),
    BLACKSTAINEDGLASS(new ItemStack(Material.BLACK_STAINED_GLASS, 1)),
    BLACKGLASS(new ItemStack(Material.BLACK_STAINED_GLASS, 1)),

    GLASSPANE(new ItemStack(Material.GLASS_PANE, 1)),
    WHITESTAINEDPANE(new ItemStack(Material.WHITE_STAINED_GLASS_PANE, 1)),
    WHITESTAINEDGLASSPANE(new ItemStack(Material.WHITE_STAINED_GLASS_PANE, 1)),
    WHITEGLASSPANE(new ItemStack(Material.WHITE_STAINED_GLASS_PANE, 1)),
    ORANGESTAINEDPANE(new ItemStack(Material.ORANGE_STAINED_GLASS_PANE, 1)),
    ORANGESTAINEDGLASSPANE(new ItemStack(Material.ORANGE_STAINED_GLASS_PANE, 1)),
    ORANGEGLASSPANE(new ItemStack(Material.ORANGE_STAINED_GLASS_PANE, 1)),
    MAGENTASTAINEDPANE(new ItemStack(Material.MAGENTA_STAINED_GLASS_PANE, 1)),
    MAGENTASTAINEDGLASSPANE(new ItemStack(Material.MAGENTA_STAINED_GLASS_PANE, 1)),
    MAGENTAGLASSPANE(new ItemStack(Material.MAGENTA_STAINED_GLASS_PANE, 1)),
    LIGHTBLUESTAINEDPANE(new ItemStack(Material.LIGHT_BLUE_STAINED_GLASS_PANE, 1)),
    LIGHTBLUESTAINEDGLASSPANE(new ItemStack(Material.LIGHT_BLUE_STAINED_GLASS_PANE, 1)),
    LIGHTBLUEGLASSPANE(new ItemStack(Material.LIGHT_BLUE_STAINED_GLASS_PANE, 1)),
    YELLOWSTAINEDPANE(new ItemStack(Material.YELLOW_STAINED_GLASS_PANE, 1)),
    YELLOWSTAINEDGLASSPANE(new ItemStack(Material.YELLOW_STAINED_GLASS_PANE, 1)),
    YELLOWGLASSPANE(new ItemStack(Material.YELLOW_STAINED_GLASS_PANE, 1)),
    LIMESTAINEDPANE(new ItemStack(Material.LIME_STAINED_GLASS_PANE, 1)),
    LIMESTAINEDGLASSPANE(new ItemStack(Material.LIME_STAINED_GLASS_PANE, 1)),
    LIMEGLASSPANE(new ItemStack(Material.LIME_STAINED_GLASS_PANE, 1)),
    PINKSTAINEDPANE(new ItemStack(Material.PINK_STAINED_GLASS_PANE, 1)),
    PINKSTAINEDGLASSPANE(new ItemStack(Material.PINK_STAINED_GLASS_PANE, 1)),
    PINKGLASSPANE(new ItemStack(Material.PINK_STAINED_GLASS_PANE, 1)),
    GRAYSTAINEDPANE(new ItemStack(Material.GRAY_STAINED_GLASS_PANE, 1)),
    GRAYSTAINEDGLASSPANE(new ItemStack(Material.GRAY_STAINED_GLASS_PANE, 1)),
    GRAYGLASSPANE(new ItemStack(Material.GRAY_STAINED_GLASS_PANE, 1)),
    LIGHTGRAYSTAINEDPANE(new ItemStack(Material.LIGHT_GRAY_STAINED_GLASS_PANE, 1)),
    LIGHTGRAYSTAINEDGLASSPANE(new ItemStack(Material.LIGHT_GRAY_STAINED_GLASS_PANE, 1)),
    LIGHTGRAYGLASSPANE(new ItemStack(Material.LIGHT_GRAY_STAINED_GLASS_PANE, 1)),
    CYANSTAINEDPANE(new ItemStack(Material.CYAN_STAINED_GLASS_PANE, 1)),
    CYANSTAINEDGLASSPANE(new ItemStack(Material.CYAN_STAINED_GLASS_PANE, 1)),
    CYANGLASSPANE(new ItemStack(Material.CYAN_STAINED_GLASS_PANE, 1)),
    PURPLESTAINEDPANE(new ItemStack(Material.PURPLE_STAINED_GLASS_PANE, 1)),
    PURPLESTAINEDGLASSPANE(new ItemStack(Material.PURPLE_STAINED_GLASS_PANE, 1)),
    PURPLEGLASSPANE(new ItemStack(Material.PURPLE_STAINED_GLASS_PANE, 1)),
    BLUESTAINEDPANE(new ItemStack(Material.BLUE_STAINED_GLASS_PANE, 1)),
    BLUESTAINEDGLASSPANE(new ItemStack(Material.BLUE_STAINED_GLASS_PANE, 1)),
    BLUEGLASSPANE(new ItemStack(Material.BLUE_STAINED_GLASS_PANE, 1)),
    BROWNSTAINEDPANE(new ItemStack(Material.BROWN_STAINED_GLASS_PANE, 1)),
    BROWNSTAINEDGLASSPANE(new ItemStack(Material.BROWN_STAINED_GLASS_PANE, 1)),
    BROWNGLASSPANE(new ItemStack(Material.BROWN_STAINED_GLASS_PANE, 1)),
    GREENSTAINEDPANE(new ItemStack(Material.GREEN_STAINED_GLASS_PANE, 1)),
    GREENSTAINEDGLASSPANE(new ItemStack(Material.GREEN_STAINED_GLASS_PANE, 1)),
    GREENGLASSPANE(new ItemStack(Material.GREEN_STAINED_GLASS_PANE, 1)),
    REDSTAINEDPANE(new ItemStack(Material.RED_STAINED_GLASS_PANE, 1)),
    REDSTAINEDGLASSPANE(new ItemStack(Material.RED_STAINED_GLASS_PANE, 1)),
    REDGLASSPANE(new ItemStack(Material.RED_STAINED_GLASS_PANE, 1)),
    BLACKSTAINEDPANE(new ItemStack(Material.BLACK_STAINED_GLASS_PANE, 1)),
    BLACKSTAINEDGLASSPANE(new ItemStack(Material.BLACK_STAINED_GLASS_PANE, 1)),
    BLACKGLASSPANE(new ItemStack(Material.BLACK_STAINED_GLASS_PANE, 1)),

    CLAY(new ItemStack(Material.CLAY)),
    HARDCLAY(new ItemStack(Material.TERRACOTTA)),
    WHITETERRACOTA(new ItemStack(Material.WHITE_TERRACOTTA, 1)),
    ORANGETERRACOTA(new ItemStack(Material.ORANGE_TERRACOTTA, 1)),
    MAGENTATERRACOTA(new ItemStack(Material.MAGENTA_TERRACOTTA, 1)),
    LIGHTBLUETERRACOTA(new ItemStack(Material.LIGHT_BLUE_TERRACOTTA, 1)),
    YELLOWTERRACOTA(new ItemStack(Material.YELLOW_TERRACOTTA, 1)),
    LIMETERRACOTA(new ItemStack(Material.LIME_TERRACOTTA, 1)),
    PINKTERRACOTA(new ItemStack(Material.PINK_TERRACOTTA, 1)),
    GRAYTERRACOTA(new ItemStack(Material.GRAY_TERRACOTTA, 1)),
    LIGHTGRAYTERRACOTA(new ItemStack(Material.LIGHT_GRAY_TERRACOTTA, 1)),
    CYANTERRACOTA(new ItemStack(Material.CYAN_TERRACOTTA, 1)),
    PURPLETERRACOTA(new ItemStack(Material.PURPLE_TERRACOTTA, 1)),
    BLUETERRACOTA(new ItemStack(Material.BLUE_TERRACOTTA, 1)),
    BROWNTERRACOTA(new ItemStack(Material.BROWN_TERRACOTTA, 1)),
    GREENTERRACOTA(new ItemStack(Material.GREEN_TERRACOTTA, 1)),
    REDTERRACOTA(new ItemStack(Material.RED_TERRACOTTA, 1)),
    BLACKTERRACOTA(new ItemStack(Material.BLACK_TERRACOTTA, 1)),

    DANDELION(new ItemStack(Material.DANDELION, 1)),
    POPPY(new ItemStack(Material.POPPY, 1)),
    ORCHID(new ItemStack(Material.BLUE_ORCHID, 1)),
    BLUEORCHID(new ItemStack(Material.BLUE_ORCHID, 1)),
    ALLIUM(new ItemStack(Material.ALLIUM, 1)),
    AZURE(new ItemStack(Material.AZURE_BLUET, 1)),
    AZUREBLUET(new ItemStack(Material.AZURE_BLUET, 1)),
    TULIP(new ItemStack(Material.RED_TULIP, 1)),
    REDTULIP(new ItemStack(Material.RED_TULIP, 1)),
    ORANGETULIP(new ItemStack(Material.ORANGE_TULIP, 1)),
    WHITETULIP(new ItemStack(Material.WHITE_TULIP, 1)),
    PINKTULIP(new ItemStack(Material.PINK_TULIP, 1)),
    DAISY(new ItemStack(Material.OXEYE_DAISY, 1)),
    OXYEDAISY(new ItemStack(Material.OXEYE_DAISY, 1)),

    SLAB(new ItemStack(Material.STONE_SLAB, 1)),
    STONESLAB(new ItemStack(Material.STONE_SLAB, 1)),
    SANDSTONESLAB(new ItemStack(Material.SANDSTONE_SLAB, 1)),
    COBBLESLAB(new ItemStack(Material.COBBLESTONE_SLAB, 1)),
    COBBLESTONESLAB(new ItemStack(Material.COBBLESTONE_SLAB, 1)),
    BRICKSLAB(new ItemStack(Material.STONE_BRICK_SLAB, 1)),
    STONEBRICKSLAB(new ItemStack(Material.STONE_BRICK_SLAB, 1)),
    NETHERBRICKSLAB(new ItemStack(Material.NETHER_BRICK_SLAB, 1)),
    NETHERSLAB(new ItemStack(Material.NETHER_BRICK_SLAB, 1)),
    QUARTZSLAB(new ItemStack(Material.QUARTZ_SLAB, 1)),

    OAKSTAIRS(new ItemStack(Material.OAK_STAIRS, 1)),
    COBBLESTAIRS(new ItemStack(Material.COBBLESTONE_STAIRS, 1)),
    BRICKSTAIRS(new ItemStack(Material.BRICK_STAIRS, 1)),
    STONEBRICKSTAIRS(new ItemStack(Material.STONE_BRICK_STAIRS, 1)),
    NETHERBRICKSTAIRS(new ItemStack(Material.NETHER_BRICK_STAIRS, 1)),
    SPRUCESTAIRS(new ItemStack(Material.SPRUCE_STAIRS, 1)),
    BIRCHSTAIRS(new ItemStack(Material.BIRCH_STAIRS, 1)),
    JUNGLESTAIRS(new ItemStack(Material.JUNGLE_STAIRS, 1)),
    QUARTZSTAIRS(new ItemStack(Material.QUARTZ_STAIRS, 1)),
    ACACIASTAIRS(new ItemStack(Material.ACACIA_STAIRS, 1)),
    DARKOAKSTAIRS(new ItemStack(Material.DARK_OAK_STAIRS, 1)),
    REDSANDSTONESTAIRS(new ItemStack(Material.RED_SANDSTONE_STAIRS, 1)),

    STONEBUTTON(new ItemStack(Material.STONE_BUTTON, 1)),
    WOODBUTTON(new ItemStack(Material.OAK_BUTTON, 1)),

    STONEPRESUREPLATE(new ItemStack(Material.STONE_PRESSURE_PLATE, 1)),
    STONEPLATE(new ItemStack(Material.STONE_PRESSURE_PLATE, 1)),
    WOODPRESUREPLATE(new ItemStack(Material.OAK_PRESSURE_PLATE, 1)),
    WOODPLATE(new ItemStack(Material.OAK_PRESSURE_PLATE, 1)),
    GOLDPRESUREPLATE(new ItemStack(Material.LIGHT_WEIGHTED_PRESSURE_PLATE, 1)),
    GOLDPLATE(new ItemStack(Material.LIGHT_WEIGHTED_PRESSURE_PLATE, 1)),
    IRONPRESUREPLATE(new ItemStack(Material.HEAVY_WEIGHTED_PRESSURE_PLATE, 1)),
    IRONPLATE(new ItemStack(Material.HEAVY_WEIGHTED_PRESSURE_PLATE, 1)),

    QUARTZBLOCK(new ItemStack(Material.QUARTZ_BLOCK, 1)),
    CHISLEDQUARTZBLOCK(new ItemStack(Material.QUARTZ_BLOCK, 1)),
    PILLARQUARTZBLOCK(new ItemStack(Material.QUARTZ_BLOCK, 1)),

    // combat
    DIAMONDSWORD(new ItemStack(Material.DIAMOND_SWORD, 1)),
    GOLDENDSWORD(new ItemStack(Material.GOLDEN_SWORD, 1)),
    GOLDSWORD(new ItemStack(Material.GOLDEN_SWORD, 1)),
    IRONSWORD(new ItemStack(Material.IRON_SWORD, 1)),
    STONESWORD(new ItemStack(Material.STONE_SWORD, 1)),
    WOODSWORD(new ItemStack(Material.WOODEN_SWORD, 1)),
    WOODENSWORD(new ItemStack(Material.WOODEN_SWORD, 1)),

    DIAMONDAXE(new ItemStack(Material.DIAMOND_AXE, 1)),
    GOLDENDAXE(new ItemStack(Material.GOLDEN_AXE, 1)),
    GOLDAXE(new ItemStack(Material.GOLDEN_AXE, 1)),
    IRONAXE(new ItemStack(Material.IRON_AXE, 1)),
    STONEAXE(new ItemStack(Material.STONE_AXE, 1)),
    WOODAXE(new ItemStack(Material.WOODEN_AXE, 1)),
    WOODENAXE(new ItemStack(Material.WOODEN_AXE, 1)),

    DIAMONDPICKAXE(new ItemStack(Material.DIAMOND_PICKAXE, 1)),
    GOLDENDPICKAXE(new ItemStack(Material.GOLDEN_PICKAXE, 1)),
    GOLDPICKAXE(new ItemStack(Material.GOLDEN_PICKAXE, 1)),
    IRONPICKAXE(new ItemStack(Material.IRON_PICKAXE, 1)),
    STONEPICKAXE(new ItemStack(Material.STONE_PICKAXE, 1)),
    WOODPICKAXE(new ItemStack(Material.WOODEN_PICKAXE, 1)),
    WOODENPICKAXE(new ItemStack(Material.WOODEN_PICKAXE, 1)),

    DIAMONDSHOVEL(new ItemStack(Material.DIAMOND_SHOVEL, 1)),
    GOLDENDSHOVEL(new ItemStack(Material.GOLDEN_SHOVEL, 1)),
    GOLDSHOVEL(new ItemStack(Material.GOLDEN_SHOVEL, 1)),
    IRONSHOVEL(new ItemStack(Material.IRON_SHOVEL, 1)),
    STONESHOVEL(new ItemStack(Material.STONE_SHOVEL, 1)),
    WOODSHOVEL(new ItemStack(Material.WOODEN_SHOVEL, 1)),
    WOODENSHOVEL(new ItemStack(Material.WOODEN_SHOVEL, 1)),

    DIAMONDHOE(new ItemStack(Material.DIAMOND_HOE, 1)),
    GOLDENDHOE(new ItemStack(Material.GOLDEN_HOE, 1)),
    GOLDHOE(new ItemStack(Material.GOLDEN_HOE, 1)),
    IRONHOE(new ItemStack(Material.IRON_HOE, 1)),
    STONEHOE(new ItemStack(Material.STONE_HOE, 1)),
    WOODHOE(new ItemStack(Material.WOODEN_HOE, 1)),
    WOODENHOE(new ItemStack(Material.WOODEN_HOE, 1)),

    LEATHERHELMET(new ItemStack(Material.LEATHER_HELMET, 1)),
    LEATHERCHESTPLATE(new ItemStack(Material.LEATHER_CHESTPLATE, 1)),
    LEATHERLEGGINGS(new ItemStack(Material.LEATHER_LEGGINGS, 1)),
    LEATHERBOOTS(new ItemStack(Material.LEATHER_BOOTS, 1)),

    GOLDHELMET(new ItemStack(Material.GOLDEN_HELMET, 1)),
    GOLDENHELMET(new ItemStack(Material.GOLDEN_HELMET, 1)),
    GOLDCHESTPLATE(new ItemStack(Material.GOLDEN_CHESTPLATE, 1)),
    GOLDENCHESTPLATE(new ItemStack(Material.GOLDEN_CHESTPLATE, 1)),
    GOLDLEGGINGS(new ItemStack(Material.GOLDEN_LEGGINGS, 1)),
    GOLDENLEGGINGS(new ItemStack(Material.GOLDEN_LEGGINGS, 1)),
    GOLDBOOTS(new ItemStack(Material.GOLDEN_BOOTS, 1)),
    GOLDENBOOTS(new ItemStack(Material.GOLDEN_BOOTS, 1)),

    IRONHELMET(new ItemStack(Material.IRON_HELMET, 1)),
    IRONCHESTPLATE(new ItemStack(Material.IRON_CHESTPLATE, 1)),
    IRONLEGGINGS(new ItemStack(Material.IRON_LEGGINGS, 1)),
    IRONBOOTS(new ItemStack(Material.IRON_BOOTS, 1)),

    CHAINMAILHELMET(new ItemStack(Material.CHAINMAIL_HELMET, 1)),
    CHAINHELMET(new ItemStack(Material.CHAINMAIL_HELMET, 1)),
    CHAINMAILCHESTPLATE(new ItemStack(Material.CHAINMAIL_CHESTPLATE, 1)),
    CHAINCHESTPLATE(new ItemStack(Material.CHAINMAIL_CHESTPLATE, 1)),
    CHAINMAILLEGGINGS(new ItemStack(Material.CHAINMAIL_LEGGINGS, 1)),
    CHAINLEGGINGS(new ItemStack(Material.CHAINMAIL_LEGGINGS, 1)),
    CHAINMAILBOOTS(new ItemStack(Material.CHAINMAIL_BOOTS, 1)),
    CHAINBOOTS(new ItemStack(Material.CHAINMAIL_BOOTS, 1)),

    DIAMONDHELMET(new ItemStack(Material.DIAMOND_HELMET, 1)),
    DIAMONDCHESTPLATE(new ItemStack(Material.DIAMOND_CHESTPLATE, 1)),
    DIAMONDLEGGINGS(new ItemStack(Material.DIAMOND_LEGGINGS, 1)),
    DIAMONDBOOTS(new ItemStack(Material.DIAMOND_BOOTS, 1)),

    // foodstuff
    GOLDCARROT(new ItemStack(Material.GOLDEN_CARROT, 1)),
    GOLDENCARROT(new ItemStack(Material.GOLDEN_CARROT, 1)),
    GOLDAPPLE(new ItemStack(Material.GOLDEN_APPLE, 1)),
    GAPPLE(new ItemStack(Material.GOLDEN_APPLE, 1)),
    CRAPPLE(new ItemStack(Material.GOLDEN_APPLE, 1)),
    GOLDENAPPLE(new ItemStack(Material.GOLDEN_APPLE, 1)),
    GODAPPLE(new ItemStack(Material.GOLDEN_APPLE, 1)),
    NOTCHAPPLE(new ItemStack(Material.GOLDEN_APPLE, 1)),
    RAWBEEF(new ItemStack(Material.BEEF, 1)),
    BEEF(new ItemStack(Material.BEEF, 1)),
    RAWMEAT(new ItemStack(Material.BEEF, 1)),
    MEAT(new ItemStack(Material.BEEF, 1)),
    STEAK(new ItemStack(Material.COOKED_BEEF, 1)),
    COOKEDBEEF(new ItemStack(Material.COOKED_BEEF, 1)),
    COOKEDMEAT(new ItemStack(Material.COOKED_BEEF, 1)),
    RAWCHICKEN(new ItemStack(Material.CHICKEN, 1)),
    COOKEDCHICKEN(new ItemStack(Material.COOKED_CHICKEN, 1)),
    PORKCHOP(new ItemStack(Material.COOKED_PORKCHOP, 1)),
    COOKEDPORKCHOP(new ItemStack(Material.COOKED_PORKCHOP, 1)),
    COOKEDPORK(new ItemStack(Material.COOKED_PORKCHOP, 1)),
    RAWMUTTON(new ItemStack(Material.MUTTON, 1)),
    COOKEDMUTTON(new ItemStack(Material.COOKED_MUTTON, 1)),
    RAWRABBIT(new ItemStack(Material.RABBIT, 1)),
    COOKEDRABBIT(new ItemStack(Material.COOKED_RABBIT, 1)),
    FISH(new ItemStack(Material.COD, 1)),
    SALMON(new ItemStack(Material.SALMON, 1)),
    CLOWNFISH(new ItemStack(Material.TROPICAL_FISH, 1)),
    PUFFERFISH(new ItemStack(Material.COD, 1)),
    COOKEDFISH(new ItemStack(Material.COOKED_COD, 1)),
    COOKEDSALMON(new ItemStack(Material.COOKED_SALMON, 1)),
    BAKEDPOTATO(new ItemStack(Material.BAKED_POTATO, 1)),
    POISONEDPOTATO(new ItemStack(Material.POISONOUS_POTATO, 1)),
    POSIONPOTATO(new ItemStack(Material.POISONOUS_POTATO, 1)),
    SPIDEREYE(new ItemStack(Material.SPIDER_EYE, 1)),
    MUSHROOMSOUP(new ItemStack(Material.MUSHROOM_STEW, 1)),
    MUSHROOMSTEW(new ItemStack(Material.MUSHROOM_STEW, 1)),
    SOUP(new ItemStack(Material.MUSHROOM_STEW, 1)),
    RABBITSOUP(new ItemStack(Material.RABBIT_STEW, 1)),
    RABBITSTEW(new ItemStack(Material.RABBIT_STEW, 1)),
    PIE(new ItemStack(Material.PUMPKIN_PIE, 1)),
    ROTTENFLESH(new ItemStack(Material.ROTTEN_FLESH, 1)),

    // bucket
    WATER(new ItemStack(Material.WATER_BUCKET, 1)),
    WATERBUCKET(new ItemStack(Material.WATER_BUCKET, 1)),
    LAVA(new ItemStack(Material.LAVA_BUCKET, 1)),
    LAVABUCKET(new ItemStack(Material.LAVA_BUCKET, 1)),

    // misc
    DRAGONEGG(new ItemStack(Material.DRAGON_EGG, 1)),
    MUSHROOM(new ItemStack(Material.RED_MUSHROOM, 1)),
    REDMUSHROOM(new ItemStack(Material.RED_MUSHROOM, 1)),
    BROWNMUSHROOM(new ItemStack(Material.BROWN_MUSHROOM, 1)),
    MOSSSTONE(new ItemStack(Material.MOSSY_COBBLESTONE, 1)),
    CRAFTINGTABLE(new ItemStack(Material.CRAFTING_TABLE, 1)),
    PEARL(new ItemStack(Material.ENDER_PEARL, 1)),
    ENDERPEARL(new ItemStack(Material.ENDER_PEARL, 1)),
    LILLYPAD(new ItemStack(Material.LILY_PAD, 1)),
    LILLY(new ItemStack(Material.LILY_PAD, 1)),
    SNOW(new ItemStack(Material.SNOW_BLOCK, 1)),
    SNOWBALL(new ItemStack(Material.SNOWBALL, 1)),
    CLAYBALL(new ItemStack(Material.CLAY_BALL, 1)),
    MELON(new ItemStack(Material.MELON_SLICE, 1)),
    ENCHANTTABLE(new ItemStack(Material.ENCHANTING_TABLE, 1)),
    ENDPORTAL(new ItemStack(Material.END_PORTAL_FRAME, 1)),
    ENDERCHEST(new ItemStack(Material.ENDER_CHEST, 1)),
    TRAPPEDCHEST(new ItemStack(Material.TRAPPED_CHEST, 1)),
    NETHERSTAR(new ItemStack(Material.NETHER_STAR, 1)),
    TRIPWIRE(new ItemStack(Material.TRIPWIRE_HOOK, 1)),
    TRIPWIREHOOK(new ItemStack(Material.TRIPWIRE_HOOK, 1)),
    STICKYPISTON(new ItemStack(Material.STICKY_PISTON, 1)),
    COBWEB(new ItemStack(Material.COBWEB, 1)),
    DEADBUSH(new ItemStack(Material.DEAD_BUSH, 1)),
    SNOWBLOCK(new ItemStack(Material.SNOW_BLOCK, 1)),
    NAMETAG(new ItemStack(Material.NAME_TAG, 1)),
    FLINTANDSTEEL(new ItemStack(Material.FLINT_AND_STEEL, 1)),
    FLINTSTEEL(new ItemStack(Material.FLINT_AND_STEEL, 1)),
    FNS(new ItemStack(Material.FLINT_AND_STEEL, 1)),
    LIGHTER(new ItemStack(Material.FLINT_AND_STEEL, 1)),
    FISHINGROD(new ItemStack(Material.FISHING_ROD, 1)),
    ROD(new ItemStack(Material.FISHING_ROD, 1)),
    MELONBLOCK(new ItemStack(Material.MELON, 1)),
    MELONSLICE(new ItemStack(Material.MELON_SLICE, 1)),
    WETSPONGE(new ItemStack(Material.SPONGE, 1)),
    LAPIS(new ItemStack(Material.LAPIS_LAZULI, 1)),
    LAPISLAZULI(new ItemStack(Material.LAPIS_LAZULI, 1)),
    COMMANDBLOCK(new ItemStack(Material.COMMAND_BLOCK, 1)),
    CMD(new ItemStack(Material.COMMAND_BLOCK, 1)),
    COMMAND_BLOCK(new ItemStack(Material.COMMAND_BLOCK, 1)),

    // colorful(gay) bed
    BED(new ItemStack(Material.RED_BED, 1)),
    WHITEBED(new ItemStack(Material.WHITE_BED, 1)),
    ORANGEBED(new ItemStack(Material.ORANGE_BED, 1)),
    MAGENTABED(new ItemStack(Material.MAGENTA_BED, 1)),
    LIGHTBLUEBED(new ItemStack(Material.LIGHT_BLUE_BED, 1)),
    YELLOWBED(new ItemStack(Material.YELLOW_BED, 1)),
    LIMEBED(new ItemStack(Material.LIME_BED, 1)),
    PINKBED(new ItemStack(Material.PINK_BED, 1)),
    GRAYBED(new ItemStack(Material.GRAY_BED, 1)),
    LIGHTGRAYBED(new ItemStack(Material.LIGHT_GRAY_BED, 1)),
    CYANBED(new ItemStack(Material.CYAN_BED, 1)),
    PURPLEBED(new ItemStack(Material.PURPLE_BED, 1)),
    BLUEDBED(new ItemStack(Material.BLUE_BED, 1)),
    BROWNBED(new ItemStack(Material.BROWN_BED, 1)),
    GREENBED(new ItemStack(Material.GREEN_BED, 1)),
    REDBED(new ItemStack(Material.RED_BED, 1)),
    BLACKBED(new ItemStack(Material.BLACK_BED, 1));

    @Getter
    ItemStack itemStack;

    LItemStack(ItemStack itemStack) {
        this.itemStack = itemStack;
    }
}
